=== adithkkn/CAT_2_WSD/univ.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="Christ">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" name="computerscience">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="studentname" type="xs:string" />
              <xs:element name="studentuniversity" type="xs:string" />
              <xs:element name="studentphone" type="xs:unsignedLong" />
              <xs:element name="studentemail" type="xs:string" />
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

=== adithkkn/CAT_2_WSD/univ.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="univ.xsl"?>
<Christ xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="univ.xsd">

   <computerscience>
      <studentname>govind</studentname>
      <studentuniversity>Bengaluru</studentuniversity>
      <studentphone>9876666677</studentphone>
      <studentemail>govind@christuniv.in</studentemail>
   </computerscience>

   <computerscience>
      <studentname>aravind</studentname>
      <studentuniversity>bengaluru</studentuniversity>
      <studentphone>1234567654</studentphone>
      <studentemail>arav@christuniv.in</studentemail>
   </computerscience>


   <computerscience>
      <studentname>kumar</studentname>
      <studentuniversity>delhi</studentuniversity>
      <studentphone>8787656545</studentphone>
      <studentemail>kumar@christuniv.in</studentemail>
   </computerscience>
</Christ>
